### PR TITLE
NTP-8307

### PR DESCRIPTION
**Pull request by angelkbrown**
Add a param to `shift_time` to allow skipping the time of day shift, so that times of day set in the db or `seed_dump` file may be preserved.

### CODE REVIEW

**Review by ninjascribble — APPROVED** [review]
Looks good! I didn't realize we were referencing GC/NCC classes directly in this gem. When in Rome... 😜

**Comment by ninjascribble** [comment]
@angelkbrown Any thoughts on merging this into `master` instead of `rails3`? Or rather... any thoughts on why we're using `rails3` instead of `master`?

**Comment by jesseclark** [comment]
Can someone remove me from this repo?

**Comment by ninjascribble** [comment]
@jesseclark Looks like you're listed as a watcher on this repo. I can't delist you, but you should be able to unwatch it yourself 👍

**Comment by jesseclark** [comment]
Ah. Thanks, @ninjascribble. I didn't realize this was a public repo.

**Comment by djantzen** [comment]
Open Source baby! I just know you wanna contribute!

**Comment by adrianpike** [comment]
@jesseclark additional eyes needed for review plz

**Comment by jesseclark** [comment]
Do y'all really want me to forward this thread to outages@?

**Comment by angelkbrown** [comment]
@ninjascribble No idea on why we're using that branch. Maybe renaming the `rails3` branch to `master` would be best/easiest.

**Comment by ninjascribble** [comment]
I want to do a little bit of local testing on this before merging it in, but it's probably a good one to keep open 👍

**Comment by ninjascribble** [comment]
This is nearly two years old, and I'm not sure it's relevant anymore. Gonna go ahead and close it out.

**Pull request closed without merging**
